{{- if .Values.alerting.recordingRules -}}
{{- $datasourceUid := include "observability.datasourceUid" . -}}
{{- $namespace := include "observability.namespace" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
    labels:
        {{- include "observability.labels" . | nindent 8 }}
        grafana_alert: "true"
    name: {{ printf "%s-recording-rules" (include "observability.fullname" .) | trunc 63 | trimSuffix "-" | quote }}
    namespace: {{ $namespace | quote }}
data:
    recording-rules.yaml: |
        apiVersion: 1
        groups:
            -   orgId: 1
                name: liferay-recording-rules
                folder: {{ .Values.alerting.folder | quote }}
                interval: {{ .Values.alerting.interval | quote }}
                rules:
                    {{- range $key, $rule := .Values.alerting.recordingRules }}
                    -   uid: {{ $key | quote }}
                        title: {{ $rule.record | quote }}
                        record: {{ $rule.record | quote }}
                        data:
                            -   refId: A
                                datasourceUid: {{ $datasourceUid | quote }}
                                model:
                                    datasource:
                                        type: prometheus
                                        uid: {{ $datasourceUid | quote }}
                                    expr: |
                                        {{- $rule.expr | nindent 40 }}
                                    refId: A
                    {{- end }}
{{- end -}}
