{{- if .Values.alloy.enabled -}}
{{- if ne .Values.alloy.namespace (include "observability.namespace" .) -}}
apiVersion: v1
kind: Namespace
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-10"
    labels:
        {{- include "observability.labels" . | nindent 8 }}
        pod-security.kubernetes.io/enforce: restricted
    name: {{ .Values.alloy.namespace | quote }}
{{- end -}}
{{- end -}}
