{{- if .Values.alloy.enabled -}}
{{- $cloud := include "observability.cloudProvider" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    {{- $awsArn := .Values.alloy.iam.awsRoleArn -}}
    {{- $gcpSa := .Values.alloy.iam.gcpServiceAccount -}}
    {{- if or (and (eq $cloud "aws") $awsArn) (and (eq $cloud "gcp") $gcpSa) }}
    annotations:
        {{- if and (eq $cloud "aws") $awsArn }}
        eks.amazonaws.com/role-arn: {{ $awsArn | quote }}
        {{- end }}
        {{- if and (eq $cloud "gcp") $gcpSa }}
        iam.gke.io/gcp-service-account: {{ $gcpSa | quote }}
        {{- end }}
    {{- end }}
    labels:
        {{- include "observability.labels" . | nindent 8 }}
    name: liferay-alloy
    namespace: {{ include "observability.namespace" . | quote }}
{{- end -}}
