{{- if .Values.lpkg.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ .Values.lpkg.claimName }}
    namespace: {{ include "liferay.namespace" . }}
spec:
    accessModes:
        -   ReadWriteMany
    resources:
        requests:
            storage: {{ .Values.lpkg.storageSize }}
    {{- with .Values.lpkg.storageClassName }}
    storageClassName: {{ . }}
    {{- end }}
{{- end }}